gradle.properties
grails-app/controllers/io/xh/hoist/impl/HoistImplController.groovy
grails-app/domain/io/xh/hoist/config/AppConfig.groovy
grails-app/init/io/xh/hoist/BootStrap.groovy
grails-app/services/io/xh/hoist/config/ConfigService.groovy
grails-app/services/io/xh/hoist/track/TrackService.groovy
src/main/groovy/io/xh/hoist/util/Utils.groovy

Still need to test the config differ.  But these changes are pretty definite.  Instructions for migrating to this new scenario are in the ticket.

Unwind multi-environment config concept

---

README.md
build.gradle

plugin is being moved to hoist-sencha
react apps will have header set by nginx

remove x-frame-options plugin

---

grails-app/services/io/xh/hoist/log/LogArchiveService.groovy

https://github.com/exhi/hoist-core/issues/32

Log Archiver - Supports names with dash and underscore

---

grails-app/controllers/io/xh/hoist/admin/PreferenceAdminController.groovy
grails-app/domain/io/xh/hoist/feedback/Feedback.groovy
grails-app/domain/io/xh/hoist/pref/Preference.groovy
grails-app/domain/io/xh/hoist/pref/UserPreference.groovy
grails-app/init/io/xh/hoist/BootStrap.groovy
grails-app/services/io/xh/hoist/config/ConfigService.groovy
grails-app/services/io/xh/hoist/pref/PrefService.groovy

DB's will require:
ALTER TABLE xh_preference ADD group_name VARCHAR(255);
UPDATE xh_preference SET group_name = 'Default' WHERE group_name IS NULL;
ALTER TABLE xh_preference MODIFY group_name VARCHAR(255) NOT NULL;

Add group field for Preferences, Fixes #25

---

grails-app/init/io/xh/hoist/BootStrap.groovy
grails-app/services/io/xh/hoist/email/EmailService.groovy

+revert bootstrap change that deals with this

EmailService accounts for defaultDomain without @, Fixes #43

---

grails-app/controllers/io/xh/hoist/impl/HoistImplController.groovy

+ Requires client toolkit updates to submit clientUsername as required
+ Fixes #46

Ensure client and session user in sync for relevant HoistImpl endpoints

---

src/main/groovy/io/xh/hoist/AppEnvironment.groovy

Additional AppEnvironment enums for UAT+BCP

---

grails-app/controllers/io/xh/hoist/impl/XhController.groovy
src/main/groovy/io/xh/hoist/util/Utils.groovy

See comments in corresponding hoist-react PR: https://github.com/exhi/hoist-react/pull/877

Display datasource info in Admin (Fixes hoist-react #829)

---

src/main/groovy/io/xh/hoist/util/InstanceConfigUtils.groovy

InstanceConfigUtils warns if cannot find/read file

---

grails-app/services/io/xh/hoist/track/TrackService.groovy
grails-app/services/io/xh/hoist/user/IdentityService.groovy

+ Passing incorrect message vs. msg config to trackService silently failed to persist the track log entry.
+ Update TrackService to log an error on write failure within async block.

Fix track logging for impersonation

---

grails-app/init/io/xh/hoist/BootStrap.groovy
grails-app/services/io/xh/hoist/monitor/MonitoringService.groovy
src/main/groovy/io/xh/hoist/log/LogUtils.groovy

- create new appender for MonitoringService only
- log results each time all Monitors are run

Log monitor results

---

grails-app/controllers/io/xh/hoist/impl/XhController.groovy
src/main/groovy/io/xh/hoist/exception/NotAuthorizedException.groovy

See https://github.com/exhi/hoist-react/issues/675

Throw custom SessionMismatchException.

---

CHANGELOG.md
grails-app/init/io/xh/hoist/BootStrap.groovy

Bootstrap default config+pref for AutoRefreshSvc

---

grails-app/init/io/xh/hoist/BootStrap.groovy

Addresses HoistReact Issue [#1201](https://github.com/exhi/hoist-react/issues/1201): new Pref with full control over VersionBar
co PR: HoistReact Pull [#1223](https://github.com/exhi/hoist-react/pull/1223)

Version Bar Footer

---

CHANGELOG.md
src/main/groovy/io/xh/hoist/json/JSONSerializer.java
src/main/groovy/io/xh/hoist/json/serializer/GStringSerializer.java

 Dedicated Jackson serializer for GString

---

CHANGELOG.md
src/main/groovy/io/xh/hoist/log/LogSupport.groovy
src/main/groovy/io/xh/hoist/util/Timer.groovy

+ Enhance logErrorCompact message.

+ Allow Timer to fire at higher frequencies (down to 500ms)

---

grails-app/services/io/xh/hoist/export/GridExportImplService.groovy

See https://github.com/exhi/hoist-react/issues/1343

Support (optionally) setting a different exportFormat per cell when exporting to Excel

---

CHANGELOG.md
grails-app/controllers/io/xh/hoist/impl/XhController.groovy
grails-app/init/io/xh/hoist/BootStrap.groovy
grails-app/services/io/xh/hoist/user/IdentityService.groovy

Server-side changes of this issue:
https://github.com/xh/hoist-core/issues/96

Impersonation config

---

CHANGELOG.md
grails-app/controllers/io/xh/hoist/impl/XhController.groovy
src/main/groovy/io/xh/hoist/util/Utils.groovy

+ Fixes #50 (at least as far as hoist-core is concerned)

Include appBuild tag in xh/version output

---

CHANGELOG.md
build.gradle
src/main/groovy/io/xh/hoist/util/Utils.groovy

This parser claims to adhere exactly to the spec and it's passed every test case I've thrown at it so far.

Switch to using nanoJson

---

grails-app/controllers/io/xh/hoist/BaseController.groovy
src/main/groovy/io/xh/hoist/exception/ExceptionRenderer.groovy
src/main/groovy/io/xh/hoist/exception/NotFoundException.groovy

+ NotFound is not a RoutineException.
+ Related cleanups, tightening to logging

Exception Fixes, tightening

---

grails-app/controllers/io/xh/hoist/impl/XhController.groovy
src/main/groovy/io/xh/hoist/util/Utils.groovy

+ Serialize with server environment info to capture server startup time.

Add Utils.startupTime

---

grails-app/services/io/xh/hoist/export/GridExportImplService.groovy

See issue: https://github.com/xh/hoist-core/issues/94

Set row color based on tree depth when exporting tree grids

---

build.gradle
grails-app/services/io/xh/hoist/export/GridExportImplService.groovy

See issue https://github.com/xh/hoist-core/issues/138

Upgrade Apache POI to 4.1.2.

---

grails-app/init/io/xh/hoist/BootStrap.groovy

Replace int `xhIdleTimeoutMins` config with json `xhIdleTimeouts` config.
See hoist-react PR: https://github.com/xh/hoist-react/pull/1946
See toolbox PR: https://github.com/xh/toolbox/pull/406

IdleService changes

---

src/main/groovy/io/xh/hoist/monitor/MonitorResult.groovy

This PR is a small addition in tandem with Hoist React PR https://github.com/xh/hoist-react/pull/2055 to address issue [#2050](https://github.com/xh/hoist-react/issues/2050)

Add active flag to monitor result

---

grails-app/controllers/io/xh/hoist/admin/JsonBlobAdminController.groovy
grails-app/controllers/io/xh/hoist/jsonblob/JsonBlobController.groovy
grails-app/domain/io/xh/hoist/jsonblob/JsonBlob.groovy
grails-app/services/io/xh/hoist/jsonblob/JsonBlobService.groovy

See hoist-react PR: https://github.com/xh/hoist-react/pull/2067

Add JsonBlob domain class, service and controllers

---

grails-app/controllers/io/xh/hoist/impl/XhController.groovy
grails-app/domain/io/xh/hoist/jsonblob/JsonBlob.groovy
grails-app/services/io/xh/hoist/jsonblob/JsonBlobService.groovy

JsonBlob has an owner, rather than a username.
See hoist-react PR: https://github.com/xh/hoist-react/pull/2080

JsonBlob Owners

---

grails-app/controllers/io/xh/hoist/admin/JsonBlobAdminController.groovy
grails-app/controllers/io/xh/hoist/impl/XhController.groovy
grails-app/domain/io/xh/hoist/jsonblob/JsonBlob.groovy
grails-app/services/io/xh/hoist/jsonblob/JsonBlobService.groovy

+ Implement ACL in JsonBlobService
+ Remove JsonBlob.valueLastUpdated
See hoist-react PR: https://github.com/xh/hoist-react/pull/2092

JsonBlob ACL

---

grails-app/controllers/io/xh/hoist/admin/JsonBlobDiffAdminController.groovy
grails-app/services/io/xh/hoist/jsonblob/JsonBlobDiffService.groovy

See hoist-react PR: https://github.com/xh/hoist-react/pull/2097

Add remote diff functionality to JsonBlob admin

---

grails-app/controllers/io/xh/hoist/impl/XhController.groovy
grails-app/domain/io/xh/hoist/jsonblob/JsonBlob.groovy
grails-app/services/io/xh/hoist/jsonblob/JsonBlobService.groovy

See hoist-react PR: https://github.com/xh/hoist-react/pull/2102

Add UUID column to JsonBlobs

---

grails-app/controllers/io/xh/hoist/impl/XhController.groovy
grails-app/domain/io/xh/hoist/jsonblob/JsonBlob.groovy
grails-app/services/io/xh/hoist/jsonblob/JsonBlobService.groovy

See hoist-react PR: https://github.com/xh/hoist-react/pull/2108
Replace JsonBlobService.delete() with JsonBlobService.archive()

Add 'archived' flag to JsonBlob

---

CHANGELOG.md
grails-app/controllers/io/xh/hoist/admin/JsonBlobAdminController.groovy
grails-app/domain/io/xh/hoist/jsonblob/JsonBlob.groovy
grails-app/services/io/xh/hoist/jsonblob/JsonBlobDiffService.groovy
grails-app/services/io/xh/hoist/jsonblob/JsonBlobService.groovy

+ Add archivedDate to JsonBlob
+ Add unique constraint across name/type/owner/archivedDate
+ Match jsonBlobs diffs using this constraint
See hoist-react PR: https://github.com/xh/hoist-react/pull/2141

JsonBlob - ArchivedDate

---

CHANGELOG.md
grails-app/controllers/io/xh/hoist/impl/XhController.groovy
grails-app/domain/io/xh/hoist/jsonblob/JsonBlob.groovy
grails-app/services/io/xh/hoist/jsonblob/JsonBlobService.groovy

See hoist-react PR: https://github.com/xh/hoist-react/pull/2164

Add JsonBlob meta column

---

CHANGELOG.md
grails-app/services/io/xh/hoist/jsonblob/JsonBlobService.groovy

This PR closes https://github.com/xh/hoist-core/issues/184

Add owner and acl to create and update method parameters

---

CHANGELOG.md
grails-app/services/io/xh/hoist/export/GridExportImplService.groovy
grails-app/services/io/xh/hoist/track/TrackService.groovy
grails-app/services/io/xh/hoist/user/IdentityService.groovy
src/main/groovy/io/xh/hoist/exception/ExceptionRenderer.groovy
src/main/groovy/io/xh/hoist/log/LogSupport.groovy
src/main/groovy/io/xh/hoist/log/LogUtils.groovy
src/main/groovy/io/xh/hoist/util/Utils.groovy

One thing I wasn't *quite* sure about was the format of the username, and whether we want to tag it with a `user:` prefix.  I think we should stay out of the business of tagging right now, but happy to discuss.
Also note the removal of the "[log on trace for more...]".  Happy to discuss that of course but would like to propose dropping that.  
Think its a pretty simple story we have to answer the question "how do I get more information about exceptions in the log"

Enhancements to Logging and Exception Logging

---

grails-app/controllers/io/xh/hoist/BaseController.groovy
grails-app/controllers/io/xh/hoist/security/AccessInterceptor.groovy
grails-app/services/io/xh/hoist/BaseService.groovy
grails-app/services/io/xh/hoist/user/IdentityService.groovy

+ Track start and stop within impersonation session for clarity
+ Use fixed messages with data field for better analysis
+ misc. cleanups to use new username getter
+ be sure to always log ending of impersonation session when moving from user to user.
+ log events to main log/standard out

Fix to impersonation tracking

---

CHANGELOG.md
src/main/groovy/io/xh/hoist/util/DateTimeUtils.groovy

+ Incorrect use of D (day of year) vs d (day of month).

Fix string format constants on DateTimeUtils

---

grails-app/init/io/xh/hoist/BootStrap.groovy

See hoist-react PR: https://github.com/xh/hoist-react/pull/2609

Use JSON for xhSizingMode preference, keyed by platform

---

CHANGELOG.md
grails-app/controllers/io/xh/hoist/admin/LogViewerAdminController.groovy
grails-app/services/io/xh/hoist/log/LogReaderService.groovy

Closes #181
Should be merged with matching PR in hoist-react: https://github.com/xh/hoist-react/pull/2712

Option to download log files

---

CHANGELOG.md
grails-app/controllers/io/xh/hoist/RestController.groovy
grails-app/controllers/io/xh/hoist/admin/EhCacheAdminController.groovy
grails-app/controllers/io/xh/hoist/admin/LogViewerAdminController.groovy
grails-app/controllers/io/xh/hoist/admin/ServiceAdminController.groovy
grails-app/services/io/xh/hoist/BaseService.groovy
grails-app/services/io/xh/hoist/alertbanner/AlertBannerService.groovy
grails-app/services/io/xh/hoist/clienterror/ClientErrorService.groovy
grails-app/services/io/xh/hoist/config/ConfigDiffService.groovy
grails-app/services/io/xh/hoist/config/ConfigService.groovy
grails-app/services/io/xh/hoist/email/EmailService.groovy
grails-app/services/io/xh/hoist/export/GridExportImplService.groovy
grails-app/services/io/xh/hoist/http/BaseProxyService.groovy
grails-app/services/io/xh/hoist/jsonblob/JsonBlobDiffService.groovy
grails-app/services/io/xh/hoist/log/LogArchiveService.groovy
grails-app/services/io/xh/hoist/log/LogLevelService.groovy
grails-app/services/io/xh/hoist/monitor/MonitoringService.groovy
grails-app/services/io/xh/hoist/pref/PrefDiffService.groovy
grails-app/services/io/xh/hoist/pref/PrefService.groovy
grails-app/services/io/xh/hoist/security/BaseAuthenticationService.groovy
grails-app/services/io/xh/hoist/track/TrackService.groovy
grails-app/services/io/xh/hoist/user/IdentityService.groovy
grails-app/services/io/xh/hoist/websocket/WebSocketService.groovy
src/main/groovy/io/xh/hoist/cache/Cache.groovy
src/main/groovy/io/xh/hoist/exception/ExceptionRenderer.groovy
src/main/groovy/io/xh/hoist/log/LogSupport.groovy
src/main/groovy/io/xh/hoist/util/Timer.groovy
src/main/groovy/io/xh/hoist/websocket/HoistWebSocketChannel.groovy

Note that I left the removal of the static versions of the methods out of the breaking changes -- I don't think there is any real usage there.  They have long caused problems to the IDE and JVM in recognizing method calls on the core methods. 
Please see also:
https://github.com/xh/toolbox/pull/539

Log changes

---

CHANGELOG.md
grails-app/controllers/io/xh/hoist/BaseController.groovy
grails-app/controllers/io/xh/hoist/admin/ConfigAdminController.groovy
grails-app/controllers/io/xh/hoist/admin/JsonBlobAdminController.groovy
grails-app/controllers/io/xh/hoist/admin/LogLevelAdminController.groovy
grails-app/controllers/io/xh/hoist/admin/MonitorAdminController.groovy
grails-app/controllers/io/xh/hoist/admin/PreferenceAdminController.groovy
grails-app/controllers/io/xh/hoist/admin/UserPreferenceAdminController.groovy
grails-app/controllers/io/xh/hoist/impl/XhController.groovy
grails-app/services/io/xh/hoist/BaseService.groovy
grails-app/services/io/xh/hoist/config/ConfigDiffService.groovy
grails-app/services/io/xh/hoist/environment/EnvironmentService.groovy
grails-app/services/io/xh/hoist/jsonblob/JsonBlobDiffService.groovy
grails-app/services/io/xh/hoist/jsonblob/JsonBlobService.groovy
grails-app/services/io/xh/hoist/pref/PrefService.groovy
grails-app/services/io/xh/hoist/security/BaseAuthenticationService.groovy
grails-app/services/io/xh/hoist/track/TrackService.groovy
grails-app/services/io/xh/hoist/user/IdentityService.groovy
src/main/groovy/io/xh/hoist/user/IdentitySupport.groovy

Resolves #220: https://github.com/xh/hoist-core/issues/220

Indicate if 'last updated by' user was being impersonated

---

CHANGELOG.md
build.gradle

Client app needs this to use in emails

Enable GSPs

---

CHANGELOG.md
grails-app/services/io/xh/hoist/clienterror/ClientErrorEmailService.groovy
grails-app/services/io/xh/hoist/clienterror/ClientErrorService.groovy
grails-app/services/io/xh/hoist/feedback/FeedbackService.groovy
grails-app/services/io/xh/hoist/track/TrackService.groovy
grails-app/services/io/xh/hoist/user/IdentityService.groovy
src/main/groovy/io/xh/hoist/util/Utils.groovy

+ Allow  tracking asynchronous server tasks done on behalf of a user.
+ Enhance client error to email user impersonation info

track/client error/feedback tweaks

---

CHANGELOG.md
grails-app/controllers/io/xh/hoist/admin/MemoryMonitorAdminController.groovy
grails-app/init/io/xh/hoist/BootStrap.groovy
grails-app/services/io/xh/hoist/monitor/MemoryMonitoringService.groovy

Enhance MemoryMonitor:
+ Add GC statistics
+ Add ability to take heap dump
+ Add pctMax as primary metric

MemoryMonitoringService enhancements

---

CHANGELOG.md
grails-app/services/io/xh/hoist/alertbanner/AlertBannerService.groovy

+ Useful for use-case where beta/production share DB.

Append environment to `xhAlertBanner` JSON blob name in non-prod envs

---

CHANGELOG.md
grails-app/controllers/io/xh/hoist/BaseController.groovy
grails-app/controllers/io/xh/hoist/RestController.groovy
grails-app/controllers/io/xh/hoist/admin/AlertBannerAdminController.groovy

New json parsing methods on BaseController

---

CHANGELOG.md
grails-app/controllers/io/xh/hoist/impl/XhController.groovy
grails-app/services/io/xh/hoist/user/BaseRoleService.groovy
grails-app/services/io/xh/hoist/user/BaseUserService.groovy
grails-app/services/io/xh/hoist/user/IdentityService.groovy
src/main/groovy/io/xh/hoist/user/HoistUser.groovy

+ Support for new 'HOIST_IMPERSONATOR' role
+ Allow customization of impersonation targets.
See matching PR in Hoist React

Improve Impersonation

---

CHANGELOG.md
grails-app/controllers/io/xh/hoist/impl/XhController.groovy
grails-app/init/io/xh/hoist/BootStrap.groovy
grails-app/services/io/xh/hoist/config/ConfigService.groovy

+ Deprecate config `xhAppVersionCheckEnabled` in favor of object based `xhAppVersionCheck`.
+ Add support for `shouldRequireRefresh` flag
See corresponding hoist-react PR: https://github.com/xh/hoist-react/pull/3407

Version checking and forcing refresh

---

grails-app/init/io/xh/hoist/BootStrap.groovy

See hoist-react PR: https://github.com/xh/hoist-react/pull/3465

Add `xhFlags` config

---

grails-app/services/io/xh/hoist/websocket/WebSocketService.groovy

Tom and I were surprised to find this extra layer of async/thread usage, given how common this operation is

Simplify WebSocket push in (common) single channel case

---

CHANGELOG.md
grails-app/services/io/xh/hoist/http/BaseProxyService.groovy

In particular, don't want late exceptions in streaming to cause hard-to-debug exceptions from trying to change already committed response.
Phase 1 for improvements to ProxyService.  Phase 2 will be better default proxying of headers

Improve Exception Handling in ProxyService

---

CHANGELOG.md
grails-app/services/io/xh/hoist/ldap/LdapService.groovy

Thanks @haynesjm42 for discovering this.

Fix bug in `LdapService.lookupUser`

---

grails-app/services/io/xh/hoist/alertbanner/AlertBannerService.groovy

+ Remove Cruft.
+ Use ReplicatedValue rather than single value cache.

Cleanup to alert banner.

---

CHANGELOG.md
src/main/groovy/io/xh/hoist/ldap/LdapGroup.groovy
src/main/groovy/io/xh/hoist/ldap/LdapObject.groovy
src/main/groovy/io/xh/hoist/ldap/LdapPerson.groovy

Move `cn`, `displayname`, `mail`, and `name` attributes to `LdapObject`

---

grails-app/services/io/xh/hoist/alertbanner/AlertBannerService.groovy
src/main/groovy/io/xh/hoist/BaseService.groovy
src/main/groovy/io/xh/hoist/cache/BaseCache.groovy
src/main/groovy/io/xh/hoist/cache/Cache.groovy
src/main/groovy/io/xh/hoist/cache/CachedValue.groovy

+ Minor updates to ctor validations
+ Doc comment tweaks
+ Set `@CompileStatic` on AlertBannerService for good measure

Proposed usage of @NamedVariant for Cache classes

---

grails-app/controllers/io/xh/hoist/impl/XhController.groovy
grails-app/init/io/xh/hoist/BootStrap.groovy
grails-app/services/io/xh/hoist/environment/EnvironmentService.groovy
src/main/groovy/io/xh/hoist/security/BaseAuthenticationService.groovy

See matching Hoist React PR here --  https://github.com/xh/hoist-react/pull/3773

Handle instance changes

---

grails-app/controllers/io/xh/hoist/RestController.groovy
grails-app/controllers/io/xh/hoist/admin/AdminRestController.groovy

Enhance RestController to support multiple datasources

---

CHANGELOG.md
grails-app/init/io/xh/hoist/ClusterConfig.groovy
grails-app/services/io/xh/hoist/clienterror/ClientErrorService.groovy
grails-app/services/io/xh/hoist/cluster/ClusterService.groovy
src/main/groovy/io/xh/hoist/BaseService.groovy
src/main/groovy/io/xh/hoist/cachedvalue/CachedValue.groovy
src/main/groovy/io/xh/hoist/util/Timer.groovy

Just doing a quick test for this in problematic environment.

All cluster configuration must be in place before instance started

---

grails-app/controllers/io/xh/hoist/admin/cluster/LogViewerAdminController.groovy

Fix return value of log viewer admin

Fix return value of log viewer admin

---

CHANGELOG.md
src/main/groovy/io/xh/hoist/websocket/HoistWebSocketChannel.groovy

Ticket https://github.com/xh/hoist-react/issues/3964
Server update for https://github.com/xh/hoist-react/pull/3966

Additional client metadata to display in admin websocket output

---

grails-app/services/io/xh/hoist/track/TrackLoggingService.groovy
grails-app/services/io/xh/hoist/track/TrackService.groovy
src/main/groovy/io/xh/hoist/track/TimestampedLogEntry.groovy

Plus some related cleanups in the logging.

Expose TrackSeverity in tracking log statements + log at that severity.
