gradle.properties
grails-app/controllers/io/xh/hoist/admin/UserAdminController.groovy
grails-app/controllers/io/xh/hoist/impl/XhController.groovy
grails-app/controllers/io/xh/hoist/security/AccessInterceptor.groovy
grails-app/services/io/xh/hoist/security/BaseAuthenticationService.groovy
grails-app/services/io/xh/hoist/user/BaseRoleService.groovy
grails-app/services/io/xh/hoist/user/BaseUserService.groovy
grails-app/services/io/xh/hoist/user/IdentityService.groovy
src/main/groovy/io/xh/hoist/user/HoistUser.groovy
src/main/groovy/io/xh/hoist/util/Utils.groovy

+ Identity service caches only username strings in session, delegates to UserService to resolve to HoistUser objects.
+ New requirement for apps to implement a RoleService (over new BaseRoleService), called by HoistUser to produce role assignments on demand and to avoid caching in the user object.
+ HoistUser no longer serializes roles in its JSONFormat to aid more efficient use of this object as a general class for data on enterprise users (which might or might not have app-level roles).
+ Methods added to BaseAuthenticationService to reduce app-level boilerplate, including revised stubs for login/logout + resource whitelisting.
+ Server <> Client API changes around checking for initial auth status.
+ Rename `HoistImplController` -> `XhController` for more consistent use of `XH` as …

Checkpoint on identity/auth/roles re-org

---

CHANGELOG.md
src/main/groovy/io/xh/hoist/util/InstanceConfigUtils.groovy

Paul and I discussed this in the context of a client app where we might well have a mixed-environment between Rancher and non-Rancher deployments.
We currently bake the JavaOpt value pointing to the instanceConfig path into the Tomcat container. We would like to be able to deploy the same container build in either environment, so we needed to make `InstanceConfigUtils` a bit more flexible and allow it to be pointed at a directory and expect to find either an `[appCode].yml` file or a collection of config files.

InstanceConfigUtils checks for [appCode].yml within specified directory

---

grails-app/controllers/io/xh/hoist/impl/XhController.groovy

Small fix to look for JSONElement instead of JSONObject here when updating preference values via the `setPrefs` endpoint.
#97

Accept JSON array or object for JSON prefs (Fixes #97)

---

CHANGELOG.md
grails-app/init/io/xh/hoist/BootStrap.groovy
grails-app/services/io/xh/hoist/monitor/MonitorResultService.groovy
grails-app/services/io/xh/hoist/monitor/MonitoringEmailService.groovy
grails-app/services/io/xh/hoist/monitor/MonitoringService.groovy

+ Add `monitorTimeoutSecs` to control max runtime of each monitor check.
+ Add `runInLocalDevMode` to enabled scheduled monitor runs during local development.
+ Tweaks to timeout/exception messages.
+ Fixes #103

Additional config support for status monitoring

---

CHANGELOG.md
src/main/groovy/io/xh/hoist/exception/ValidationException.groovy

Java seems to prohibit calling a non-static method as a parameter to super() in a constructor, e.g. super(toString()). I don't know how I committed such a broken version, but it should be fixed now.

Fix bug in ValidationException

---

grails-app/init/io/xh/hoist/BootStrap.groovy
grails-app/services/io/xh/hoist/log/LogReaderService.groovy

This PR addresses issue https://github.com/xh/hoist-core/issues/124
- Throw runtimeException on logReaderService readFile when xhEnableLogViewer config is false
- Added xhEnableLogViewer config to Bootstrap (default to true)

Disabled logReaderService endpoint and added default xhEnableLogViewer config to Bootstrap

---

grails-app/init/io/xh/hoist/BootStrap.groovy
grails-app/services/io/xh/hoist/export/GridExportImplService.groovy

See issue: #74
See corresponding hoist-react pr: https://github.com/xh/hoist-react/pull/1848
Went with a single config rather than the suggested json config, because I felt that individual configs (we currently only have one) are easier to document with the config note

Add config to adjust when excel export switches to streaming API.

---

CHANGELOG.md
grails-app/domain/io/xh/hoist/clienterror/ClientError.groovy
grails-app/domain/io/xh/hoist/pref/UserPreference.groovy
grails-app/domain/io/xh/hoist/track/TrackLog.groovy

I've noticed some poor performance loading activity tracking with some client apps. I think/hope it's reasonable to use this GORM mapping config to setup some default DB indices on fields we know we use for queries. 
I didn't want to go overboard here - we could remove the `UserPreference` index if we wanted to pare back.
If merged happy to test a snap build against a client app running on SQL Server to a) ensure this syntax doesn't cause any issues and b) verify if there is a noticeable performance improvement.

Specify DB indices for selected domain classes

---

CHANGELOG.md
grails-app/controllers/io/xh/hoist/admin/MemoryMonitorAdminController.groovy
grails-app/init/io/xh/hoist/BootStrap.groovy
grails-app/services/io/xh/hoist/monitor/MemoryMonitoringService.groovy
src/main/groovy/io/xh/hoist/util/Timer.groovy

+ Takes and stores a limited history of memory usage snapshots, based on JVM runtime stats.

Add simple MemoryMonitoringService

---

CHANGELOG.md
src/main/groovy/io/xh/hoist/json/JSONSerializer.java
src/main/groovy/io/xh/hoist/json/serializer/DoubleSerializer.java
src/main/groovy/io/xh/hoist/json/serializer/FloatSerializer.java

This is consistent with how we serialized Floats and Doubles pre-jackson, and consistent with how the react client expects to receive these numbers.

Serialize NaN and Infinity to `null`

---

grails-app/services/io/xh/hoist/export/GridExportImplService.groovy

Relates to and resolves bug for empty grid exports in https://github.com/xh/hoist-react/issues/2376
- Realized that the error stems from creating a table area of 0 -- at a minimum it must have row height of 1

Fix: Excel table area must have minimum height of 1

---

CHANGELOG.md
grails-app/services/io/xh/hoist/monitor/MonitorResultService.groovy

+ Status check implementations should be able to mark a check as failed or inactive internally - hopefully installing a message to explain - without the subsequent metric-based evaluation overwriting such a status and message.

Respect failed/inactive status set by monitors

---

CHANGELOG.md
grails-app/services/io/xh/hoist/export/GridExportImplService.groovy

+ Cache cell styles for re-use across a column's rows at the same depth (previously limited to max of 64,000 styles, and we were creating a new style for each formatted or grouped cell)
+ Remove obsolete code to downgrade XSSF workbooks to SXSSF workbook due to style constraints

Make 'excelTable' downgrades to 'excel' obsolete

---

CHANGELOG.md
grails-app/services/io/xh/hoist/export/GridExportImplService.groovy

Discussed w/Lee yesterday - will revisit how to make tree grid exports more performant. In the meantime, we do need the streamingCellThreshold to downgrade large exports (realized the limitation in performance was not style-related, though the change to cache groupedColors prevents the apache error of exceeding 64k styles)

Unwind removing use of streamingCellThreshold to downgrade excelTable

---

grails-app/init/io/xh/hoist/BootStrap.groovy

Add `xhSizingMode` pref to store the built-in sizing mode
See hoist-react PR: https://github.com/xh/hoist-react/pull/2593
See toolbox PR: xh/toolbox#518

Build in support for sizingMode to Hoist

---

CHANGELOG.md
grails-app/services/io/xh/hoist/email/EmailService.groovy
src/main/groovy/io/xh/hoist/util/Utils.groovy

+ When running in local development mode, EmailService now requires either a filter or override config to be active, to ensure that a dev has placed some constraints on where dev emails will go.

Block sending unfiltered email from local dev

---

CHANGELOG.md
grails-app/controllers/io/xh/hoist/admin/EnvAdminController.groovy

+ See corresponding Hoist React change for new Admin Console tab to display in grid form.

New admin endpoint to output env vars and JVM system properties

---

src/main/groovy/io/xh/hoist/browser/Utils.groovy

Used this (and my own devices) to determine the correct user agent strings to look for: https://docs.microsoft.com/en-us/microsoft-edge/web-platform/user-agent-guidance#identifiers-for-microsoft-edge-on-various-platforms
Could not get my devices talking to my desktop so tested with these unit tests: 
```
@Test
void getBrowserDetectsDesktopEdge() {
assertEquals(Browser.EDGE, Utils.getBrowser("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.55 Safari/537.36 Edg/96.0.1054.41"));
}
@Test
void getBrowserDetectsAndroidEdge() {
assertEquals(Browser.EDGE, Utils.getBrowser("Mozilla/5.0 (Linux; Android 12; Pixel 4a) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.55 Mobile Safari/537.36 EdgA/96.0.1054.41"));
}
@Test
void …
```

Update user agent matchers for Edge browser

---

CHANGELOG.md

Paul noticed that our CHANGELOG between 8.5.0 > 8.6.1 requires database changes to the JsonBlob table, but the instructions are incomplete and inconsistent with the released state of the versions

Adjust CHANGELOG re: JsonBlob database migration

---

build.gradle

+ Avoid confusion with local development in "wrapper" mode, with both hoist-core and an app setup in a multi-project gradle build.
+ Devs should ensure they run `bootRun` from their app-specific gradle scope, not the combined top-level scope created by the wrapper.

Throw if bootRun task run against plugin

---

CHANGELOG.md
grails-app/services/io/xh/hoist/user/IdentityService.groovy

Hard to find but an easy fix. 
We were accidentally setting the session[APPARENT_USER_KEY] to the authUser object itself rather than its authUser.username string. This object was being converted into the desired username string so the bug was not apparent until server restart. The intended string values of session[APPARENT_USER_KEY] and session[AUTH_USER_KEY] are being properly persisted through a server restart, but the erroneous object value of session[APPARENT_USER_KEY] was not persisted during a server restart and was defaulting to null, resulting in the NullPointerException error.

Impersonation + Server Restart bug fix

---

grails-app/services/io/xh/hoist/jsonblob/JsonBlobDiffService.groovy

This fixes a bug that Petra found when trying to update a json blob from a diff view.
This method now mirrors the setup in [grails-app/services/io/xh/hoist/pref/PrefDiffService.groovy](https://github.com/xh/hoist-core/blob/develop/grails-app/services/io/xh/hoist/pref/PrefDiffService.groovy#L16)

Grails5 Bug Fix: Make method @Transactional

---

CHANGELOG.md
grails-app/services/io/xh/hoist/environment/EnvironmentService.groovy
src/main/groovy/io/xh/hoist/util/DateTimeUtils.groovy

+ App/server timezone conversion utils default to current day/date if called without arguments.
+ Added static getAppZoneId / getServerZoneId convenience getters

`DateTimeUtils` tweak to support no-arg calls

---

CHANGELOG.md
grails-app/services/io/xh/hoist/pref/PrefService.groovy

+ With SQL logging enabled, I noticed we were issuing one `select` per non-local preference when a user visited the app.
+ Second-level query caching mitigated this, but only after a given user had visited at least once to populate the cache for their username.
+ Now only a single `select` is issued to fetch all user prefs at once.

Optimize `preService.clientConfig`

---

CHANGELOG.md
grails-app/services/io/xh/hoist/monitor/MonitorResultService.groovy
src/main/groovy/io/xh/hoist/monitor/MonitorResult.groovy

Small change to the way the Monitor sets the results.message variable on failure. It will now prepend the error, warn, or fail message but still always render the user-provided message afterwards, rather than overriding it. 
Backwards and forwards compatible:
Old hoist-core + new hoist-react = appears identical to old behavior, the non-success message overrides any user-provided
New hoist-core + old hoist-react = the messages on the monitor card are displayed on the same line, rather than a newline
Closes #268

Monitor message will be prefixed instead of overriden on failure

---

.editorconfig
CHANGELOG.md
grails-app/services/io/xh/hoist/export/GridExportImplService.groovy
grails-app/services/io/xh/hoist/log/LogReaderService.groovy
src/main/groovy/io/xh/hoist/log/LogSupport.groovy

+ Avoid need to cast return types out of `withInfo` and friends.
+ Changelog formatting for consistent line length, .editorconfig to set automatically.

Improve LogSupport signatures w/generics

---

CHANGELOG.md
grails-app/services/io/xh/hoist/email/EmailService.groovy

Added support for emailing attached files to the hoist-core `sendEmail()` method.

Added an `attachments` arg to EmailService.sendEmail()

---

CHANGELOG.md
grails-app/controllers/io/xh/hoist/admin/TrackLogAdminController.groovy
grails-app/controllers/io/xh/hoist/impl/XhController.groovy
grails-app/init/io/xh/hoist/BootStrap.groovy
grails-app/services/io/xh/hoist/track/TrackService.groovy

New `xhActivityTrackingConfig` w/constraints for safer TrackLog creation/querying
+ Partial mitigation of a major TrackService pitfall - querying and serializing large numbers of TrackLogs that themselves contain large nested `data` maps requires a significant allocation of memory and in the worst case can crash the server.
+ New config limits maximum size of tracked data and provides configurable (and lowered) constraints on admin client querying.
+ Intended for use with corresponding hoist-react v56 updates to respect the same config on the client.

Safer TrackLog creation/querying

---

CHANGELOG.md
grails-app/init/io/xh/hoist/BootStrap.groovy
src/main/groovy/io/xh/hoist/util/DateTimeUtils.groovy

+ Callable from e.g. app Bootstrap routines to enforce a particular time zone, if required by the app (e.g. due to interactions with a database running in a particular zone).
+ Log default zone in Hoist banner message on startup.
+ Fixes #215

New DateTimeUtils.ensureServerTimeZoneIs() util method

---

CHANGELOG.md
grails-app/init/io/xh/hoist/BootStrap.groovy
grails-app/services/io/xh/hoist/environment/EnvironmentService.groovy
src/main/groovy/io/xh/hoist/util/DateTimeUtils.groovy

+ Auto-create config if required with default value of UTC.
+ Validate that the configured zone matches that of the JVM runtime, and throw a fatal exception to block server startup if it does not.
+ Update default `xhAppTimeZone` config value to UTC also (from GMT) - will only apply to brand-new instances, but seems a bit more standard/correct.
+ Removed static util previously added in #289 - this check goes farther than that change - it will be run automatically w/o requiring developers to update anything, and uses the config for increased visibility.

Read and enforce new `xhExpectedServerTimeZone` config in Bootstrap

---

CHANGELOG.md
grails-app/controllers/io/xh/hoist/admin/ConnectionPoolMonitorAdminController.groovy
grails-app/init/io/xh/hoist/BootStrap.groovy
grails-app/services/io/xh/hoist/monitor/ConnectionPoolMonitoringService.groovy

* Lightweight monitoring collection of JDBC connection pool statistics, including counters for active vs idle connections. Available via a new Admin Console tab for apps on `hoist-react >= 59.0`.
* Bootstrap new config to control the same.

New ConnectionPoolMonitoringService

---

grails-app/controllers/io/xh/hoist/admin/AlertBannerAdminController.groovy

Requests to create or update alerts banner are currently being run through an OWASP encoder to escape HTML content tags, `&<>` prior to saving. The banner message is then saved with the escaped character, e.g. "P&L" becomes "P&amp;L". This string will still render correctly in the banner component, however saving the message further (like toggling active status) will have a cascading effect of the `&` being encoded again, making the message "P&amp;amp;L". which will then appear in the rendered banner as "P&amp;L". 
This PR removes safe encoding, because it does not actually provide defense against cross site scripting in its current use. Security when rendering the message is still ensured through the safe-by-default [react-markdown library](https://github.com/remarkjs/react-markdown) …

Remove safe encoding when parsing alert banner requests

---

grails-app/controllers/io/xh/hoist/admin/RoleAdminController.groovy
grails-app/services/io/xh/hoist/role/provided/DefaultRoleAdminService.groovy
grails-app/services/io/xh/hoist/role/provided/DefaultRoleUpdateService.groovy
src/main/groovy/io/xh/hoist/role/provided/DefaultRoleService.groovy

+ HOIST_ROLE_MANAGER no longer granted to HOIST_ADMIN
+ API cleanup -- rename and hide defaultRoleEditService

Tweaks to `DefaultRoleService`

---

CHANGELOG.md
grails-app/services/io/xh/hoist/role/provided/DefaultRoleUpdateService.groovy
src/main/groovy/io/xh/hoist/role/provided/DefaultRoleService.groovy

It was called `ensureUserHasRoles`, but accepts only one role and name is ambiguous.
I've renamed it to `assignRole`.
This would be a breaking change.  Corresponding toolbox PR is: https://github.com/xh/toolbox/pull/697

Name of method ensureUserHasRoles is misleading

---

CHANGELOG.md
grails-app/controllers/io/xh/hoist/admin/ClientErrorAdminController.groovy
grails-app/controllers/io/xh/hoist/impl/XhController.groovy
grails-app/domain/io/xh/hoist/clienterror/ClientError.groovy
grails-app/domain/io/xh/hoist/track/TrackLog.groovy
grails-app/services/io/xh/hoist/clienterror/ClientErrorAdminService.groovy
grails-app/services/io/xh/hoist/track/TrackService.groovy

This PR adds new fields to TrackLog and ClientError databases to consolidate the two (to the extent that it makes sense)
It also refactors the `XhController` endpoints for `track` and `submitError` to expect the input parameters to be posted as JSON to the request body. One note about this change, because of the current implementation of the `ensureClientUsernameMatchesSession` method, `clientUsername` still needs to be posted to the server as a `param`. 
Finally, this server-side change refactors the `ClientErrorAdminController` to use a new service, the `ClientErrorAdminService`, to use filters provided by the client to do server-side filtering (this pattern is used in `TrackLogAdminController` and `TrackLogAdminService`).

Harmonize TrackLog and ClientError

---

CHANGELOG.md
grails-app/services/io/xh/hoist/monitor/MonitorEvalService.groovy
grails-app/services/io/xh/hoist/monitor/MonitorReportService.groovy
grails-app/services/io/xh/hoist/monitor/MonitorService.groovy
src/main/groovy/io/xh/hoist/monitor/AggregateMonitorResult.groovy
src/main/groovy/io/xh/hoist/monitor/MonitorConfig.groovy
src/main/groovy/io/xh/hoist/monitor/MonitorResult.groovy
src/main/groovy/io/xh/hoist/monitor/MonitorStatusReport.groovy

+ Type `MonitorResult.metric` as `Number`
+ Rename MonitorsResults -> AggregateMonitorResult for clarity
+ New MonitorConfig class to formalize expected definition and types of required Hoist appConfig.
+ Apply `@GrailsCompileStatic` to services.
+ Additional doc comments.

Code cleanups and smaller refactors to monitoring

---

src/main/groovy/io/xh/hoist/role/provided/DefaultRoleService.groovy

Currently, if a roleMember is present with roleMember.type==ROLE and an invalid/missing roleMember.name (one that does not match the Role.name of any Role), the DefaultRoleService will completely crash/fail, locking everyone out of the application.
This doesn't ever happen in normal operations/using the roles UI, but may happen if an application is manually changing roles/roleMembers (ie, migrating roles).

Fixed DefaultRoleService completely failing if presented with a bad roleMember

---

src/main/groovy/io/xh/hoist/BaseService.groovy

I have noticed that exceptions thrown by implementations of `BaseService.init()` using the `BaseService.parallelInit()` method do not show their full stack trace. This was because we were cutting off the exception "history" in `BaseService.initialize()`.

Fixed BaseService.initialize() hiding stack trace for init exceptions

---

src/main/groovy/io/xh/hoist/user/BaseUserService.groovy

Currently, BaseUserService does not allow the implementation to use it's own User:
```groovy
class AppUser extends HoistUser { ... 
```
```groovy
class UserService extends BaseUserService {
// This does not build, because the return type of `List<AppUser> ` is incompatible with `List<HoistUser>`
@Override
List<AppUser> list(boolean activeOnly) { ... 
```
With this fix, the app's UserService is allowed to type its own methods.

BaseUserService now allows app implementation to use the app's User type

---

CHANGELOG.md
grails-app/services/io/xh/hoist/ldap/LdapService.groovy
src/main/groovy/io/xh/hoist/ldap/LdapPerson.groovy

* LdapService `searchOne` and `searchMany` methods have been made public.
* LdapPerson class now includes `displayName`, `givenname`, and `sn` fields.
* LdapPerson class `email` key changed to `mail` to match LDAP attribute.
This branch's changes have been tested in a client app that needed these changes.

LdapService & LdapPerson Improvements

---

CHANGELOG.md
src/main/groovy/io/xh/hoist/ldap/LdapGroup.groovy
src/main/groovy/io/xh/hoist/ldap/LdapObject.groovy
src/main/groovy/io/xh/hoist/ldap/LdapPerson.groovy

Remove compileStatic annotation.
It was preventing the `keys` call in the LdapObject `populate` method from using the subclass' `getKeys` method.
CompileStatic was added recently in this commit https://github.com/xh/hoist-core/pull/364/commits/2c85e6ab644d95f53b91d6cd490aa76ff3cac7ad merged in this PR: https://github.com/xh/hoist-core/pull/364
The bug was found by a client using the `findGroups` method. He noticed that the `member` key on the retuned`LdapGroup` result was always `null`.  The `findGroups` method is not used in any production code, so this does not require an urgent release.
This does not affect the  `DefaultRoleService` because it uses the `lookupGroupMembers` method.

Remove compileStatic annotation.

---

CHANGELOG.md
grails-app/domain/io/xh/hoist/role/provided/Role.groovy
grails-app/init/io/xh/hoist/ClusterConfig.groovy

Should be a simplification and more straightforward use of the hazelcast config API.  The get methods already do clone the current configuration and "add" a new configuration.  I think we may have been thrown off with a very specific bug around the failure to deep clone evictionConfig

Fix configuration of Hazelcast distributed objects

---

src/main/groovy/io/xh/hoist/monitor/provided/DefaultMonitorDefinitionService.groovy

The existing query, `SELECT * FROM xh_monitor WHERE code = 'xhDbConnectionMonitor' LIMIT 1`, does not work in SQL Server (Microsoft SQL).
The equivalent statement in SQL Server would be `SELECT TOP(1) * FROM xh_monitor WHERE code = 'xhDbConnectionMonitor'`
I propose we simplify it to the SQL statement `SELECT * FROM xh_monitor WHERE code = 'xhDbConnectionMonitor'`, which should work in all dialects.

Simplified the xhDbConnectionMonitor query to work with more SQL dialects

---

CHANGELOG.md
grails-app/services/io/xh/hoist/environment/EnvironmentService.groovy

Fixes the issue where the log would never call because `configZoneId` given a bad `xhAppTimeZone` value would return the `defaultZone`. This would then be considered valid as an available ID by the conditional and therefore not log if we use the default or not.

Clarify `EnvironmentService` handling of invalid `xhAppTimeZone` config

---

CHANGELOG.md
grails-app/services/io/xh/hoist/email/EmailService.groovy

Went way too deep down this rabbit hole -- but there was nothing else to do but finish it

Improve `EmailService` subjects generated for non-prod / overridden deliveries

---

src/main/groovy/io/xh/hoist/cache/BaseCache.groovy
src/main/groovy/io/xh/hoist/cache/Cache.groovy
src/main/groovy/io/xh/hoist/cache/CachedValue.groovy
src/main/groovy/io/xh/hoist/util/DateTimeUtils.groovy

+ Was looking for equiv of `Cache.getEntry(k).dateEntered`.
+ Although this new getter and new `Cache.getTimestamp(k)` respect optional `timestampFn`.
+ New `DateTimeUtils.toEpochMilli()`.
+ Support passing Instants to the above + existing `intervalElapsed()`.
+ Additional OCD tweaks to / standardization of docstrings.

`CachedValue.timestamp` + minor `DateTimeUtils` updates

---

CHANGELOG.md
src/main/groovy/io/xh/hoist/cache/BaseCache.groovy
src/main/groovy/io/xh/hoist/cache/Cache.groovy
src/main/groovy/io/xh/hoist/cache/CachedValue.groovy
src/main/groovy/io/xh/hoist/cache/HzEntryListener.groovy

The hz event handler itself was triggering more serialization!  Skip it, unless we are going to do something with it.

Improvements to serialization efficiency of replicated `Cache` and `CachedValue`

---

CHANGELOG.md
grails-app/controllers/io/xh/hoist/UrlMappings.groovy
grails-app/controllers/io/xh/hoist/impl/XhController.groovy
src/main/groovy/io/xh/hoist/security/BaseAuthenticationService.groovy

+ `ping` now about as minimal as possible - no longer aliased to `version` so no longer reading a config.
+ Remove pre-existing `ping` properties from `version` endpoint (timestamp, success:true) - nothing has ever expected those from `version`

Expose `/xh/ping` as whitelisted route for uptime/reachability checks

---

CHANGELOG.md
grails-app/services/io/xh/hoist/admin/ConnectionPoolMonitoringService.groovy
grails-app/services/io/xh/hoist/admin/MemoryMonitoringService.groovy
grails-app/services/io/xh/hoist/admin/ServiceManagerService.groovy
grails-app/services/io/xh/hoist/alertbanner/AlertBannerService.groovy
grails-app/services/io/xh/hoist/clienterror/ClientErrorService.groovy
grails-app/services/io/xh/hoist/config/ConfigService.groovy
grails-app/services/io/xh/hoist/feedback/FeedbackEmailService.groovy
grails-app/services/io/xh/hoist/ldap/LdapService.groovy
grails-app/services/io/xh/hoist/log/LogArchiveService.groovy
grails-app/services/io/xh/hoist/log/LogLevelService.groovy
grails-app/services/io/xh/hoist/monitor/MonitorService.groovy
src/main/groovy/io/xh/hoist/BaseService.groovy
src/main/groovy/io/xh/hoist/cache/BaseCache.groovy
src/main/groovy/io/xh/hoist/cache/Cache.groovy
src/main/groovy/io/xh/hoist/cache/CachedValue.groovy
src/main/groovy/io/xh/hoist/role/provided/DefaultRoleService.groovy
src/main/groovy/io/xh/hoist/util/Timer.groovy

+ New BaseService factory methods + Docs
+ Require/Check unique names for *all *service resources
+ Use NamedVariant for Timer
+ Improvements to `Timer` to avoid extra executions when primary instance changes
+ Unrelated cleanups to Timer declarations and deprecate `onTimer`
+ Logs should get archived on non-primary server as well
See also change on toolbox

Enhance Timer/Cache/CachedValues API

---

CHANGELOG.md
grails-app/controllers/io/xh/hoist/security/AccessInterceptor.groovy
src/main/groovy/io/xh/hoist/HoistFilter.groovy
src/main/groovy/io/xh/hoist/exception/ExceptionHandler.groovy
src/main/groovy/io/xh/hoist/exception/NotAuthorizedException.groovy
src/main/groovy/io/xh/hoist/security/BaseAuthenticationService.groovy
src/main/groovy/io/xh/hoist/websocket/HoistWebSocketConfigurer.groovy

More complete exception handling in AccessInterceptor, 
AuthenticatonService.allowRequest, and HoistFilter. 
Leave no request exception behind !
Auth Related exceptions are returned as opaque
Use 'NamedVariant' for handleException

Improve exception handling/rendering during auth checks

---

CHANGELOG.md
grails-app/domain/io/xh/hoist/config/AppConfig.groovy
grails-app/services/io/xh/hoist/websocket/WebSocketService.groovy
src/main/groovy/io/xh/hoist/configuration/ApplicationConfig.groovy
src/main/groovy/io/xh/hoist/util/Utils.groovy

Plus a couple of minor cleanups to how we read configuration

New application configuration: `hoist.sensitiveParamTerms`

---

CHANGELOG.md
grails-app/controllers/io/xh/hoist/impl/XhController.groovy
grails-app/domain/io/xh/hoist/track/TrackLog.groovy
grails-app/services/io/xh/hoist/track/TrackService.groovy

- Note no change to the encoding of the preferences at this time.

Support for debounced and bulk uploading of track messages

---

src/main/groovy/io/xh/hoist/role/provided/DefaultRoleService.groovy

+ Resolve possible bootstrapAdminUser setting once, on init, and log if active.
+ Simplify `getRolesForUser` accordingly - this can get called in hot loops with permission checks, want to do anything we can to keep it lean and mean.

Minor optimization to DefaultRoleService bootstrapAdminUser

---

CHANGELOG.md
src/main/groovy/io/xh/hoist/log/LogSupport.groovy

+ Only log a "started" message if logging enabled at `DEBUG` or `TRACE`, respectively.
+ Allows admins to see start messages for more important `withInfo` logs, without necessarily printing both lines for all `withDebug` calls.

Updated behavior of `withInfo` and `withDebug`

---

CHANGELOG.md
src/main/groovy/io/xh/hoist/monitor/MonitorResult.groovy
src/main/groovy/io/xh/hoist/monitor/provided/DefaultMonitorDefinitionService.groovy

New ClientErrors monitor and Monitor parameter support

---

src/main/groovy/io/xh/hoist/cache/Cache.groovy
src/main/groovy/io/xh/hoist/cachedvalue/CachedValue.groovy

Just a documentation change - each of these closures had a different signature and I was getting confused.
The Groovy `@ClosureParams` annotation is more suited for adding type hints to method parameters than to fields, it did not seem to work here. 
I settled for a custom but hopefully self-evident syntax of `{ Type1, Type2, ... -> ReturnType1 | ReturnType2 | .... }` in the field comment to explain/remind the user what closure to use in that spot.

Added closure arg types to Cache/CachedValue documentation

---

CHANGELOG.md
src/main/groovy/io/xh/hoist/configuration/LogbackConfig.groovy

For easier identification/sorting of the main log with its siblings logs on a given date.

Adjust App Log Name

---

CHANGELOG.md
grails-app/controllers/io/xh/hoist/BaseController.groovy
grails-app/controllers/io/xh/hoist/admin/MonitorResultsAdminController.groovy
grails-app/controllers/io/xh/hoist/admin/cluster/ClusterAdminController.groovy
grails-app/controllers/io/xh/hoist/admin/cluster/ConnectionPoolMonitorAdminController.groovy
grails-app/controllers/io/xh/hoist/admin/cluster/EnvAdminController.groovy
grails-app/controllers/io/xh/hoist/admin/cluster/HzObjectAdminController.groovy
grails-app/controllers/io/xh/hoist/admin/cluster/LogViewerAdminController.groovy
grails-app/controllers/io/xh/hoist/admin/cluster/MemoryMonitorAdminController.groovy
grails-app/controllers/io/xh/hoist/admin/cluster/ServiceManagerAdminController.groovy
grails-app/controllers/io/xh/hoist/admin/cluster/WebSocketAdminController.groovy
grails-app/services/io/xh/hoist/cluster/ClusterService.groovy
src/main/groovy/io/xh/hoist/cluster/ClusterJsonRequest.groovy
src/main/groovy/io/xh/hoist/cluster/ClusterJsonResponse.groovy
src/main/groovy/io/xh/hoist/cluster/ClusterRequest.groovy
src/main/groovy/io/xh/hoist/exception/ClusterExecutionException.groovy
src/main/groovy/io/xh/hoist/exception/ExceptionHandler.groovy
src/main/groovy/io/xh/hoist/websocket/HoistWebSocketChannel.groovy

Support remote Json Serialization in runOnInstance
+ Also hardened Exception transport back to calling server generally.  Had seen some exceptions failing to serialize in the past, and general theme here is to avoid serializing unknown things we don't need to.
+ Also added a fix to File Downloading, which was failing to serialize files on my local machine -- now simpler, just passes the bytes.
Great improvement suggested by Jakub -- could become especially useful for any application than needs to run various things on the primary server.   The return objects no longer need to be serializable!

Support remote Json Serialization in runOnInstance

---

grails-app/controllers/io/xh/hoist/BaseController.groovy

Brings the API in line with `runOnPrimary` and `runOnInstance`

`runOnAllInstances` takes a `ClusterJsonRequest` rather than a `ClusterRequest`

---

CHANGELOG.md
grails-app/init/io/xh/hoist/BootStrap.groovy
grails-app/services/io/xh/hoist/ldap/LdapService.groovy

Client reported that our use of `LDAP_MATCHING_RULE_IN_CHAIN` has a negative performance impact on their LDAP databases and is unnecessary when querying groups without deep nesting.  Additionally, it is proprietary to MS and therefore not suitable for other LDAP implementations. This change recurses LDAP directories with its own code by default but provides a flag on `xhLdapConfig` to enable the previous implementation in cases where an AD instance uses deeply nested groups.

Remove default use of LDAP_MATCHING_RULE_IN_CHAIN

---

CHANGELOG.md
grails-app/services/io/xh/hoist/websocket/WebSocketService.groovy
src/main/groovy/io/xh/hoist/websocket/HoistWebSocketChannel.groovy

Ticket https://github.com/xh/hoist-react/issues/3947
Server side update for https://github.com/xh/hoist-react/pull/3948

Log client app version in websocket to be displayed for admins

---

CHANGELOG.md
grails-app/services/io/xh/hoist/admin/ClusterObjectsService.groovy
src/main/groovy/io/xh/hoist/admin/ClusterObjectInfo.groovy
src/main/groovy/io/xh/hoist/admin/ClusterObjectsReport.groovy
src/main/groovy/io/xh/hoist/admin/HzAdminStats.groovy

+ Remove potentially problematic usage of emptyMap/emptyList.
+ Improve Logging
+ Use JSON serialization to harden against non-serializable implementations of getAdminStats()

Harden ClusterObjectsReports

---

CHANGELOG.md
grails-app/services/io/xh/hoist/track/TrackService.groovy
src/main/groovy/io/xh/hoist/browser/Browser.groovy
src/main/groovy/io/xh/hoist/browser/Utils.groovy

Was motivated by client using Island browser, which is now only publishing its identity using the new headers.
Also some issues with device detection for this browser, which also requires the new headers.
This also unwinds some very ancient iOS homescreen code that we believe to be obsolete.
Note that we have probably reached our limits with our custom UA sniffing -- but could not see an easily dropped in java library -- `ua-parser` and `Yauaa` would require some work around multi-threading.  For now -- just extending and simplifying our existing approach seemed pragmatic.

Use User Agent 'Hint' Headers in Browser detection.
